= Java 9 Jigsaw modules example suite
include::../../.asciidoctorconfig[]
== Example example_jerrymouse

Part of the full xref:../../README.adoc[Java 9 Jigsaw modules example] suite.

[IMPORTANT]
.Authors
====
Originally written by https://github.com/mrtnlhmnn[Martin Lehmann], https://github.com/kristines[Kristine Schaal] and https://github.com/rgrammes[Rüdiger Grammes] (cf. https://github.com/accso/java9-jigsaw-examples[original repository]).

Migrated for JPMS support documentation of Apache Maven^TM^ in the course of the https://open-elements.com/support-care-maven/[Maven Support & Care] program by https://github.com/ascheman[Gerd Aschemann] (and other team members) as https://github.com/support-and-care/java9-jigsaw-examples[forked repository].
Please add discussions, requirements, bugfixes, etc. to the fork instead of the original.
====

== What is this example about?

=== Modules in this example

TODO

=== Example shows ...

TODO

==== Loading Modules in Layers

Starter implements a primitive app server that loads modular applications from the subdirectory apps/ into their own layer under the boot layer and executes them via reflection.

For requirements on modular applications and details on storage, see apps/README.txt

* Applications are stored under apps.
Each application in its own directory "x".
Directory name = application folder name
* Configuration of the application via x/app.json
* The application's modules are located under x/mods/

e.g.

----
apps/example_requires_exports
> app.json
apps/example_requires_exports/mods
> modb.jar
> modc.jar
> modmain.jar
apps/example_hiddenmain
> app.json
apps/example_hiddenmain/mods
> ...
----

* app.json defines the root module as well as the main class and method to be started, e.g.:

[source,json]
----
{
  "rootModule": "modmain",
  "bootClass": "pkgmain.Main",
  "bootMethod": "main"
}
----

Note: "bootMethod" must be static and have String[] as parameter!

END TODO
