= Java 9 Jigsaw modules example suite
include::../../.asciidoctorconfig[]
== Example example_maven_test-whitebox

Part of the full xref:../../README.adoc[Java 9 Jigsaw modules example] suite.

[IMPORTANT]
.Authors
====
Originally written by https://github.com/mrtnlhmnn[Martin Lehmann], https://github.com/kristines[Kristine Schaal] and https://github.com/rgrammes[Rüdiger Grammes] (cf. https://github.com/accso/java9-jigsaw-examples[original repository]).

Migrated for JPMS support documentation of Apache Maven^TM^ in the course of the https://open-elements.com/support-care-maven/[Maven Support & Care] program by https://github.com/ascheman[Gerd Aschemann] (and other team members) as https://github.com/support-and-care/java9-jigsaw-examples[forked repository].
Please add discussions, requirements, bugfixes, etc. to the fork instead of the original.
====

== What is this example about?

=== Modules in this example

* modmain, and org.apache.commons.lang3 from a maven dependency
* modmain has a Main class which is started in `run.sh`

=== Example shows ...

* Compilation, test compilation and execution with Maven
* Whitebox test via patching the module `modmain` with classes in `src/test/`java

The Maven compile plugin and the surefire plugin now use the patch options to compile and run test classes as part of the module to be tested.
For an example using the patch options explicitly, see xref:../example_test/README.adoc[here].
It finds out that the patch options are needed because there is no `module-info.java` in `src/main/test`.
It then parses the module name from the `module-info.java` in `src/main/java`.

Note: No Eclipse support for this example, just clean/compile/run via scripts
Note: No JavaDoc generation for this example

=== Setup

You might want to edit the Maven settings file `mvn_settings.xml` according to your needs (proxies, local repository path etc.)
The file provided here is just a copy of the original file from Maven 3.5.2 distribution.

=== Maven plugins

* A maven-compiler-plugin (version >= 3.6.2) is needed (because we need the new patch options)
* Note that the maven-compiler-plugin (version 3.6.2) currently has a bug ("syntax error") when there are comments in the `module-info.java`
* The current surefire-plugin does not yet support modules.
It runs tests in classpath mode.
