:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
== Example example_maven_blackbox

Part of the full xref:../../README.adoc[Java 9 Jigsaw modules example] suite.

[IMPORTANT]
.Authors
====
Originally written by https://github.com/mrtnlhmnn[Martin Lehmann], https://github.com/kristines[Kristine Schaal] and https://github.com/rgrammes[Rüdiger Grammes] (cf. https://github.com/accso/java9-jigsaw-examples[original repository]).

Migrated for JPMS support documentation of Apache Maven^TM^ in the course of the https://open-elements.com/support-care-maven/[Maven Support & Care] program by https://github.com/ascheman[Gerd Aschemann] (and other team members) as https://github.com/support-and-care/java9-jigsaw-examples[forked repository].
Please add discussions, requirements, bugfixes, etc. to the fork instead of the original.
====

== What is this example about?

=== Modules in this example

* modmain, moda
* modmain requires moda.

=== Example shows ...

* typical structure with maven and two modules.

Dependencies have to be modelled both in the module-info and the pom!

=== Setup

You might want to edit the Maven settings file `mvn_settings.xml` according to your needs (proxies, local repository path etc.)
The file provided here is just a copy of the original file from Maven 3.5.2 distribution.

=== Maven plugins

* maven-compiler-plugin Version >= 3.6.1 is needed
* Note that the JavaDoc generation shows an error for `modmain` (probably caused by https://issues.apache.org/jira/browse/MJAVADOC-498[this Maven plugin bug])

=== Output and Testing

This example does not use xref:../../README.adoc#golden-master-testing[golden master testing] because Maven output includes timestamps, absolute file paths, and version information that varies between runs.
See the xref:../../README.adoc#golden-master-testing[golden master testing section] in the main README for more information.
