:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
== Example example_version

Part of the full xref:../../README.adoc[Java 9 Jigsaw modules example] suite.

[IMPORTANT]
.Authors
====
Originally written by https://github.com/mrtnlhmnn[Martin Lehmann], https://github.com/kristines[Kristine Schaal] and https://github.com/rgrammes[Rüdiger Grammes] (cf. https://github.com/accso/java9-jigsaw-examples[original repository]).

Migrated for JPMS support documentation of Apache Maven^TM^ in the course of the https://open-elements.com/support-care-maven/[Maven Support & Care] program by https://github.com/ascheman[Gerd Aschemann] (and other team members) as https://github.com/support-and-care/java9-jigsaw-examples[forked repository].
Please add discussions, requirements, bugfixes, etc. to the fork instead of the original.
====

== What is this example about?

This example is not really about the Jigsaw/JPMS module system. Instead it shows that usage of the new versioning scheme.

For more background information, refer to https://openjdk.java.net/jeps/223[JEP 223].

== Sample output

This is sample output of the main class (example shown with Temurin-11.0.27+6):

----
Runtime.version() says, we are using Java version 11.0.27, build version 6
System properties say, we are using Java version as follows:
  java.version = 11.0.27
  java.runtime.version = 11.0.27+6
  java.vm.version = 11.0.27+6
  java.specification.version = 11
  java.vm.specification.version = 11
----

[NOTE]
====
The output will vary depending on your installed Java version.
This example demonstrates the version string format introduced in JEP 223 (Java 9).
====

=== Output

This example uses xref:../../README.adoc#golden-master-testing[golden master testing] to ensure output consistency.
The expected output is compared with actual output using `verify.sh`.

==== Expected Output

[source]
----
include::expected-result/run.txt[]
----

==== Actual Output

[source]
----
include::run-result/run.txt[]
----
