:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
== Example example_maven_test-blackbox

Part of the full xref:../../README.adoc[Java 9 Jigsaw modules example] suite.

[IMPORTANT]
.Authors
====
Originally written by https://github.com/mrtnlhmnn[Martin Lehmann], https://github.com/kristines[Kristine Schaal] and https://github.com/rgrammes[Rüdiger Grammes] (cf. https://github.com/accso/java9-jigsaw-examples[original repository]).

Migrated for JPMS support documentation of Apache Maven^TM^ in the course of the https://open-elements.com/support-care-maven/[Maven Support & Care] program by https://github.com/ascheman[Gerd Aschemann] (and other team members) as https://github.com/support-and-care/java9-jigsaw-examples[forked repository].
Please add discussions, requirements, bugfixes, etc. to the fork instead of the original.
====

== What is this example about?

=== Modules in this example

* modmain plus module org.apache.commons.lang3
* modmain has a Main class which is started in `run.sh`

=== Example shows ...

* Compilation, test compilation and execution with Maven
* Blackbox test with own `module-info.java` in `src/test/java`

The maven compile and surefire plugins recognize the test classes as an own module here, because there is a `module-info.java`

Note: No JavaDoc generation for this example

=== Setup

You might want to edit the Maven settings file `mvn_settings.xml` according to your needs (proxies, local repository path etc.)
The file provided here is just a copy of the original file from Maven 3.5.2 distribution.

=== Maven plugins

* maven-compiler-plugin Version >= 3.6.1 is needed
* The current surefire-plugin does not yet support modules.
It runs tests in classpath mode.

=== Output and Testing

This example does not use xref:../../README.adoc#golden-master-testing[golden master testing] because Maven output includes timestamps, absolute file paths, and version information that varies between runs.
See the xref:../../README.adoc#golden-master-testing[golden master testing section] in the main README for more information.
