= Java 9 Jigsaw modules example suite
include::../../.asciidoctorconfig[]
== Example example_naming-modules

Part of the full xref:../../README.adoc[Java 9 Jigsaw modules example] suite.

[IMPORTANT]
.Authors
====
Originally written by https://github.com/mrtnlhmnn[Martin Lehmann], https://github.com/kristines[Kristine Schaal] and https://github.com/rgrammes[Rüdiger Grammes] (cf. https://github.com/accso/java9-jigsaw-examples[original repository]).

Migrated for JPMS support documentation of Apache Maven^TM^ in the course of the https://open-elements.com/support-care-maven/[Maven Support & Care] program by https://github.com/ascheman[Gerd Aschemann] (and other team members) as https://github.com/support-and-care/java9-jigsaw-examples[forked repository].
Please add discussions, requirements, bugfixes, etc. to the fork instead of the original.
====

== What is this example about?

=== Modules in this example

* automatic-whatever, automatic-whatever2-47.11, automatic.sourcecode, java.whatever, jdk.whatever, mod-client, mod.client, mod.interface, modjava, modmain, mod_client
* modmain has a Main class which is started in run.sh

=== Example shows ...

* Naming convention for modules
* Note: No Eclipse support for this example, just clean/compile/run via scripts
* Note: No JavaDoc generation for this example
